{{- if .Values.peripheralManagerGPU }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peripheral-manager-gpu-deployment
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
    {{- include "nuvlabox-engine.peripheral-manager.labels" . | nindent 4 }}
    nuvlabox.peripheral.type: gpu
spec:
  selector:
    matchLabels:
      component: peripheral-manager-gpu
  template:
    metadata:
      labels:
        component: peripheral-manager-gpu
        {{- include "nuvlabox-engine.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: peripheral-manager-gpu
          image: "{{ .Values.images.peripheralManagerGPU.repository }}:{{ .Values.images.peripheralManagerGPU.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.peripheralManagerGPU.pullPolicy }}
          volumeMounts:
            - mountPath: /dev
              name: dev
            - mountPath: /etcfs
              name: etc
              readOnly: true
            - mountPath: /usr/lib
              name: lib
              readOnly: true
          env:
            - name: MY_NAMESPACE
              value: {{ include "nuvlabox-engine.namespace" . }}
      volumes:
        - hostPath:
            path: /dev
          name: dev
        - hostPath:
            path: /etc
          name: etc
        - hostPath:
            path: /usr/lib
          name: lib
{{- end }}