version: "3.7"

x-common: &common
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"

volumes:
  nuvlabox-db:
    driver: local
    labels:
      - "nuvlaedge.volume=True"
      - "nuvlaedge.deployment=production"

services:
  system-manager:
    <<: *common
    image: nuvlaedge/system-manager:2.6.0
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-system-manager
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-nuvlaedge}
      - NUVLAEDGE_LOG_LEVEL=${NUVLAEDGE_LOG_LEVEL:-INFO}
      - NUVLAEDGE_DATA_GATEWAY_NAME=${NUVLAEDGE_DATA_GATEWAY_NAME:-data-gateway}
      - NUVLAEDGE_DATA_GATEWAY_ENABLED=${NUVLAEDGE_DATA_GATEWAY_ENABLED:-True}
      - NUVLAEDGE_DATA_GATEWAY_IMAGE=${NUVLAEDGE_DATA_GATEWAY_IMAGE:-eclipse-mosquitto:2.0.15-openssl}
      - SKIP_MINIMUM_REQUIREMENTS=${SKIP_MINIMUM_REQUIREMENTS:-False}
      - COMPUTE_API_PORT=${COMPUTE_API_PORT:-5000}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - on-stop

  agent:
    <<: *common
    image: nuvlaedge/agent:2.10.0
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-agent
    oom_kill_disable: true
    privileged: true
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-nuvlaedge}
      - NUVLAEDGE_API_KEY=${NUVLAEDGE_API_KEY:-}
      - NUVLAEDGE_API_SECRET=${NUVLAEDGE_API_SECRET:-}
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
      - NUVLAEDGE_ENGINE_VERSION=2.6.0
      - NUVLAEDGE_LOG_LEVEL=${NUVLAEDGE_LOG_LEVEL:-INFO}
      - NUVLAEDGE_IMMUTABLE_SSH_PUB_KEY=${NUVLAEDGE_SSH_PUB_KEY:-}
      - HOST_HOME=${HOME}
      - VPN_INTERFACE_NAME=${VPN_INTERFACE_NAME:-vpn}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
      - COMPUTE_API_PORT=${COMPUTE_API_PORT:-5000}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
      - /:/rootfs:ro
    depends_on:
      - compute-api

  compute-api:
    <<: *common
    image: nuvlaedge/compute-api:1.3.0
    restart: on-failure
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-compute-api
    oom_score_adj: -900
    pid: "host"
    environment:
      - HOST=${HOSTNAME:-nuvlaedge}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlaedge/shared
    ports:
      - "${COMPUTE_API_PORT:-5000}:5000"
    healthcheck:
      test: netstat -tulpn | grep LISTEN | grep 5000 | grep socat
      interval: 20s
      timeout: 10s
      start_period: 30s

  vpn-client:
    <<: *common
    image: nuvlaedge/vpn-client:1.2.0
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-vpn-client
    oom_kill_disable: true
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun
    environment:
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent

  job-engine-lite:
    <<: *common
    image: nuvla/job-lite:3.2.7
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-job-engine-lite
    entrypoint: /app/pause.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  on-stop:
    <<: *common
    image: nuvlaedge/on-stop:1.2.0
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-on-stop
    restart: always
    command: pause
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
