version: "3.7"

x-common: &common
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlabox.component=True"
    - "nuvlabox.deployment=production"
    - "nuvlabox.peripheral.component=True"
    - "nuvlabox.peripheral.type=network"

services:
  peripheral-manager-network:
    <<: *common
    image: nuvlabox/peripheral-manager-network:1.1.2
    restart: on-failure
    network_mode: host
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    depends_on:
      - agent