version: "3.7"

x-common: &common
  stop_grace_period: 4s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlabox.component=True"
    - "nuvlabox.deployment=production"

volumes:
  nuvlabox-db:
    driver: local

networks:
  nuvlabox-shared-network:
    driver: overlay
    name: nuvlabox-shared-network
    attachable: true

services:
  data-gateway:
    <<: *common
    image: traefik:2.3.5
    container_name: datagateway
    restart: always
    oom_score_adj: -900
    command:
      - --entrypoints.mqtt.address=:1883
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - nuvlabox-shared-network

  nb-mosquitto:
    <<: *common
    image: eclipse-mosquitto:1.6.12
    container_name: nbmosquitto
    restart: always
    init: true
    command: sh -c 'sleep 10 && /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf'
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mytcprouter.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mytcprouter.entrypoints=mqtt"
      - "traefik.tcp.routers.mytcprouter.service=mosquitto"
      - "traefik.tcp.services.mosquitto.loadbalancer.server.port=1883"
      - "nuvlabox.component=True"
      - "nuvlabox.deployment=production"
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s mosquitto_sub -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
      interval: 10s
      timeout: 10s
      start_period: 10s

  system-manager:
    <<: *common
    image: nuvlabox/system-manager:1.4.1
    restart: always
    environment:
      - SKIP_MINIMUM_REQUIREMENTS=False
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlabox/shared
    ports:
      - 127.0.0.1:3636:3636
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s

  agent:
    <<: *common
    image: nuvlabox/agent:1.14.0
    restart: unless-stopped
    oom_kill_disable: true
    privileged: true
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLABOX_ENGINE_VERSION=1.14.0
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlabox/shared
      - /:/rootfs:ro
    ports:
      - 127.0.0.1:5080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    depends_on:
      - system-manager
      - compute-api

  management-api:
    <<: *common
    image: nuvlabox/management-api:1.1.1
    restart: always
    oom_score_adj: -900
    environment:
      - NUVLABOX_SSH_PUB_KEY=${NUVLABOX_SSH_PUB_KEY}
      - HOST_USER=$USER
    volumes:
      - /proc/sysrq-trigger:/sysrq
      - ${HOME}/.ssh/:/hostfs/.ssh/
      - nuvlabox-db:/srv/nuvlabox/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5001:5001

  compute-api:
    <<: *common
    image: nuvlabox/compute-api:1.1.1
    container_name: compute-api
    restart: on-failure
    oom_score_adj: -900
    pid: "host"
    environment:
      - HOST=${HOSTNAME:-nuvlabox}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nuvlabox-db:/srv/nuvlabox/shared
    ports:
      - 5000:5000
    depends_on:
      - system-manager
      - management-api
    healthcheck:
      test: netstat -tulpn | grep LISTEN | grep 5000 | grep socat
      interval: 20s
      timeout: 10s
      start_period: 30s

  network-manager:
    <<: *common
    image: nuvlabox/network-manager:1.0.0
    restart: on-failure
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - VPN_INTERFACE_NAME=${NUVLABOX_VPN_IFACE:-vpn}
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    depends_on:
      - system-manager

  vpn-client:
    <<: *common
    image: nuvlabox/vpn-client:0.0.4
    container_name: vpn-client
    restart: always
    oom_kill_disable: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
    depends_on:
      - network-manager

  security:
    <<: *common
    image: nuvlabox/security:1.0.0
    restart: on-failure
    network_mode: host
    environment:
      - EXTERNAL_CVE_VULNERABILITY_DB=${EXTERNAL_CSV_VULNERABILITY_DB:-"https://github.com/nuvla/vuln-db/blob/main/databases/all.aggregated.csv.gz?raw=true"}
      - EXTERNAL_CVE_VULNERABILITY_DB_UPDATE_INTERVAL=${EXTERNAL_CVE_VULNERABILITY_DB_UPDATE_INTERVAL:-86400}
      - SECURITY_SCAN_INTERVAL=${SECURITY_SCAN_INTERVAL:-1800}
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
