version: "3.7"

x-common: &common
  stop_grace_period: 4s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlabox.component=True"
    - "nuvlabox.deployment=production"
    - "nuvlabox.peripheral.component=True"
    - "nuvlabox.peripheral.type=modbus"

services:
  peripheral-manager-modbus:
    <<: *common
    image: nuvlabox/peripheral-manager-modbus:1.0.0
    restart: on-failure
    volumes:
      - nuvlabox-db:/srv/nuvlabox/shared
