version: "3.6"

x-common: &common
  stop_grace_period: 4s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlabox.component=True"
    - "nuvlabox.deployment=production"
    - "nuvlabox.peripheral.component=True"
    - "nuvlabox.peripheral.type=usb"

services:
  peripheral-manager-usb:
    <<: *common
    image: nuvlabox/peripheral-manager-usb:1.1.2
    restart: on-failure
    network_mode: host
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    volumes:
      - /dev:/dev:ro
      - /run/udev/control:/run/udev/control:ro
      - nuvlabox-db:/srv/nuvlabox/shared
