apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  namespace: {{ include "nuvlaedge-engine.namespace" . }}
  labels:
    {{- include "nuvlaedge-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: agent
  template:
    metadata:
      labels:
        component: agent
        {{- include "nuvlaedge-engine.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        # AGENT
        - name: agent
          image: "{{ .Values.images.agent.repository }}:{{ .Values.images.agent.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.agent.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: NUVLAEDGE_LOG_LEVEL
              value: {{ .Values.agentConfig.log_level }}
            - name: NUVLAEDGE_UUID
              value: {{ .Values.NUVLAEDGE_UUID }}
            - name: NUVLAEDGE_ENGINE_VERSION
              value: {{ .Values.images.agent.tag }}
            - name: NUVLAEDGE_EXCLUDED_MONITORS
              value: {{ .Values.agentConfig.excluded_monitors }}
            - name: NUVLAEDGE_IMMUTABLE_SSH_PUB_KEY
              value: {{ .Values.NUVLAEDGE_IMMUTABLE_SSH_PUB_KEY }}
            - name: NUVLA_ENDPOINT
              value: {{ .Values.NUVLA_ENDPOINT | default "nuvla.io" | quote }}
            - name: NUVLA_ENDPOINT_INSECURE
              value: {{ .Values.NUVLA_ENDPOINT_INSECURE | default "False" | quote }}
            - name: NUVLAEDGE_JOB_ENGINE_LITE_IMAGE
              value: "{{ .Values.images.jobEngineLite.repository }}:{{ .Values.images.jobEngineLite.tag }}"
            - name: NUVLAEDGE_VPN_COMPONENT_NAME
              value: {{ .Values.vpnClientComponentName }}
            - name: HOST_HOME
              value: {{ .Values.HOME }}
            - name: VPN_INTERFACE_NAME
              value: {{ .Values.VPN_INTERFACE_NAME | default "vpn" | quote }}
            - name: MY_HOST_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_HOST_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_NAMESPACE
              value: {{ include "nuvlaedge-engine.namespace" . }}
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
            - mountPath: /srv/nuvlaedge/shared
              name: nuvlaedge-db


      ## VOLUMES
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: nuvlaedge-db
          hostPath:
            path: /var/lib/{{ include "nuvlaedge-engine.namespace" . }}
